language: ruby
jobs:
  include:
  - stage: test
    name: Unit tests
    install:
    - gem install rspec
    script:
    - echo "Running tests against $(ruby -v)..."
    - rspec spec
  - name: Integration tests
    install:
    - gem build wash.gemspec
    - gem install wash-*.gem
    before_script:
    - curl -sfL https://github.com/puppetlabs/wash/releases/download/0.17.0/wash-0.17.0-x86_64-unknown-linux.tgz | tar -xz
    script:
    - ./wash validate examples/mock_docker.rb
